CREATE DATABASE NEGOCIOS2021;
USE NEGOCIOS2021;
/*TABLA CATEGORIA*/
CREATE TABLE CATEGORIA 
(
COD_CATE CHAR (4)NOT NULL PRIMARY KEY,
NOMBRE_CATE VARCHAR (30)NOT NULL
);

CREATE TABLE DISTRITO
(
COD_DIST			CHAR(6) NOT NULL PRIMARY KEY,
NOMBRE_DISTRITO		VARCHAR(30) NOT NULL
);
/*CREANDO LA TABLA CLIENTE*/
CREATE TABLE CLIENTE
(
DNI						CHAR(8) NOT NULL PRIMARY KEY,
APELLIDOS				VARCHAR(30) NOT NULL,
NOMBRES					VARCHAR(30) NOT NULL,
DIRECCION				VARCHAR(60) NOT NULL,
TELE_MOVIL				VARCHAR(9) 	NULL,
COD_DIS					CHAR(6) NOT NULL,
constraint FK_CODDIS FOREIGN KEY (COD_DIS)
REFERENCES DISTRITO (COD_DIST)
);


/*CREANDO LA TABLA CARGO*/
CREATE TABLE CARGO
(
COD_CARGO			CHAR(4) NOT NULL PRIMARY KEY,
NOMBRE_CARGO		VARCHAR(20) NOT NULL
);


/*CREANDO LA TABLA PRODUCTO*/
CREATE TABLE PRODUCTO
(
COD_PRODUCTO			CHAR(5) NOT NULL PRIMARY KEY,
DESCRIPCION				VARCHAR(40) NOT NULL,
PRE_UNITARIO			DECIMAL NOT NULL,
STOCK_ACTUAL			INT	NOT NULL,
PROCEDENCIA				VARCHAR(20)NOT NULL,
COD_CAT					CHAR(4) NOT NULL,
constraint FK_CODCATE FOREIGN KEY (COD_CAT)
REFERENCES CATEGORIA (COD_CATE)
);

/*TABLA BOLETA DE VENTA*/
CREATE TABLE BOLETAVENTA
(
NROBOLETA		CHAR(8) PRIMARY KEY NOT NULL,
FECHA_VENTA		DATE	NOT NULL,
TIPO_PAGO		VARCHAR(20) NOT NULL,
DNI_CLIE		CHAR(8) NOT NULL,
ESTADO			VARCHAR(30) NOT NULL,
TOTAL			DECIMAL(8,2) NOT NULL,
CONSTRAINT FK_DNICLIE FOREIGN KEY(DNI_CLIE) REFERENCES CLIENTE(DNI) 
);


SELECT * FROM BOLETAVENTA;

/*TABLA DETALLE DE VENTA*/
CREATE TABLE DETALLE_BOLETA
(
NROBOLE 	CHAR(8) NOT NULL,
COD_PROD	CHAR(5) NOT NULL,
CANTIDAD	INT		NOT NULL,
IMPORTE		DECIMAL(8,2)NOT NULL,
CONSTRAINT FK_NBOL FOREIGN KEY(NROBOLE)REFERENCES BOLETAVENTA(NROBOLETA),
CONSTRAINT FK_CODP FOREIGN KEY(COD_PROD)REFERENCES PRODUCTO(COD_PRODUCTO)
);

select * from DETALLE_BOLETA;

SELECT * FROM CATEGORIA;
INSERT INTO CATEGORIA VALUES('C001','ABARROTES');
INSERT INTO CATEGORIA VALUES('C002','LACTEOS');
INSERT INTO CATEGORIA VALUES('C003','BEBIDA');
SELECT  * FROM CATEGORIA;



/*INSERTANDO DISTRITOS*/
INSERT INTO DISTRITO VALUES('150132','SAN JUAN DE LURIGANCHO');
INSERT INTO DISTRITO VALUES('150125','BREÑA');
INSERT INTO DISTRITO VALUES('150150','CERCADO');
SELECT * FROM DISTRITO;

/*INSERTANDO REGISTRO A TABLA CLIENTE*/
INSERT INTO CLIENTE VALUES('40138129','VELIZ COLQUI','ROEL','AV. PROCERES DE LA INDEPENDENCIA # 123','954048759','150132');
INSERT INTO CLIENTE VALUES('16138129','VELIZ COLQUI','LOURDES','AV. PROCERES DE LA INDEPENDENCIA # 1500','978504759','150132');
INSERT INTO CLIENTE VALUES('86138570','VILLANUEVA HERRERA','BETSABE','AV. ABANCAY # 4000','990990215','150150');
SELECT * FROM CLIENTE;

/*INSERTANDO CARGO*/
INSERT INTO CARGO VALUES('CA01','ADMINISTRADOR(A)');
INSERT INTO CARGO VALUES('CA02','VENDEDOR(A)');
INSERT INTO CARGO VALUES('CA03','CONTADOR(A)');


/*INSERTANDO PRODUCTO*/
INSERT INTO PRODUCTO VALUES('P0001','ARROZ COSTEÑO - X 50',170,100,'NACIONAL','C001');
INSERT INTO PRODUCTO VALUES('P0002','ARROZ SAMAN X 50',165,80,'IMPORTADO','C001');
INSERT INTO PRODUCTO VALUES('P0003','GASEOASA INKA KOLA X 24', 26,250,'NACIONAL','C003');
INSERT INTO PRODUCTO VALUES('P0004','GASEOASA PEPSI X 6', 22,400,'NACIONAL','C003');

select * from producto	

/*PROCEDIMIENTOS ALMACENADOS*/
/*P.A. PARA LISTAR CLIENTES*/
DELIMITER $$ /*esta es un instrunccion que nos permite comenzar con procedimientos almecenados*/
CREATE PROCEDURE SP_LISTAR_CLIENTES()
BEGIN
SELECT C.DNI,
    C.APELLIDOS,
    C.NOMBRES,
    C.DIRECCION,
    C.TELE_MOVIL,
    D.NOMBRE_DISTRITO
    FROM CLIENTE C INNER JOIN DISTRITO D 
  ON C.COD_DIS=D.COD_DIST;
END;
/*COMPROBAR*/
call SP_LISTAR_CLIENTES(); /*en ves que execute se coloca call*/

/*P.A. PARA CONSULTAR UN CONSULTA POR SU DNI */



DELIMITER $$
CREATE PROCEDURE SP_CONSULTAR_CLIENTE_POR_DNI
(
NDNI CHAR (8)
)
BEGIN
SELECT C.DNI,
		C.APELLIDOS,
		C.NOMBRES,
		C.DIRECCION,
		C.TELE_MOVIL,
		D.NOMBRE_DISTRITO
FROM CLIENTE C INNER JOIN DISTRITO D
ON C.COD_DIS=D.COD_DIST WHERE C.DNI=NDNI;
END;

/*PROBANDO*/
CALL SP_CONSULTAR_CLIENTE_POR_DNI(86138570);

/*P.A. PARA ACTUALIZAR UN CLIENTE EN BASE SU DNI*/


DELIMITER $$
CREATE PROCEDURE SP_ACTUALIZA_CLIENTE(
NDNI		CHAR(8),
APE			VARCHAR(30),
NOM			VARCHAR(30),
DIREC		VARCHAR(60),
TELE		VARCHAR(10),
CODDIS		CHAR(6)
)
BEGIN
UPDATE CLIENTE SET APELLIDOS=APE,NOMBRES=NOM,DIRECCION=DIREC,TELE_MOVIL=TELE, COD_DIS=CODDIS
          WHERE DNI=NDNI;
END;


/*P.A. PARA ELIMINAR UN CLIENTE EN BASE SU DNI*/
DELIMITER $$
CREATE PROCEDURE SP_ELIMINA_CLIENTE(
NDNI		CHAR(8)
)
BEGIN
DELETE FROM CLIENTE WHERE DNI=NDNI;
END;


/*P.A. PARA LISTAR LOS DISTRITOS*/
DELIMITER $$
CREATE PROCEDURE SP_LISTAR_DISTRITOS()
BEGIN
SELECT * FROM DISTRITO;
END;

/*PROBANDO*/
CALL SP_LISTAR_DISTRITOS();



DELIMITER $$
CREATE PROCEDURE SP_REGISTRA_CLIENTE(
NDNI		CHAR(8),
APE			VARCHAR(30),
NOM			VARCHAR(30),
DIREC		VARCHAR(60),
TELE		VARCHAR(10),
CODDIS		CHAR(6)
)
BEGIN
INSERT INTO CLIENTE VALUES (NDNI,APE,NOM,DIREC,TELE, CODDIS);
END;

/*AVANZADOOOOOOOOOOOOOO*/

/*P.A. PARA REALIZAR LA TRANSACCION*/

/*P.A. PARA LISTAR LAS CATEGORIAS*/
DELIMITER $$
CREATE PROCEDURE SP_LISTAR_CATEGORIAS()
BEGIN
SELECT * FROM CATEGORIA;
END;


CALL SP_LISTAR_CATEGORIAS();



/*PA PARA CONSULTAR CLIENTE POR DNI Y APELLIDOS*/

DELIMITER $$
CREATE PROCEDURE SP_CONSULTAR_CLIENTE_D_A
(
BUSCA VARCHAR(10)
)
BEGIN
SELECT DNI,
    APELLIDOS,
    NOMBRES,
    DIRECCION
    FROM CLIENTE WHERE DNI LIKE CONCAT(BUSCA,'%') OR APELLIDOS LIKE CONCAT(BUSCA,'%');
END;

/*PROBANDO*/
CALL SP_CONSULTAR_CLIENTE_D_A('J')


/*PA PARA CONSULTAR LOS PRODUCTOS POR CATEGORIA Y DESCRICPION*/
DELIMITER $$
CREATE PROCEDURE SP_CONSULTAR_PRODUCTO_CATE_DESCRIP
(
CATE VARCHAR(30),
DESCRIP VARCHAR(30)
)
BEGIN
SELECT P.COD_PRODUCTO,
    P.DESCRIPCION,
    P.PRE_UNITARIO,
    P.STOCK_ACTUAL
    FROM PRODUCTO P INNER JOIN CATEGORIA C
       ON P.COD_CAT=C.COD_CATE WHERE C.NOMBRE_CATE=CATE
			AND P.DESCRIPCION LIKE CONCAT(DESCRIP,'%');
END;

/*PROBANDO*/
CALL SP_CONSULTAR_PRODUCTO_CATE_DESCRIP('BEBIDA','G');



/*PROCEDIMIENTOS ALMACENADOS PARA REGISTRAR BOLETA*/
/*P.A. PARA REGISTRAR BOLETAVENTA*/
DELIMITER $$
CREATE PROCEDURE SP_REGISTRAR_BOLETA
(
NBOL	CHAR(8),
FECHA	DATE,
TP		VARCHAR(20),
DNICLIE	CHAR(8),
ESTA	VARCHAR(30),
TOT		DECIMAL(8,2)
)
BEGIN
INSERT INTO BOLETAVENTA VALUES(NBOL,FECHA,TP,DNICLIE,ESTA,TOT);
END;

/*P.A. PARA REGISTRAR DETALLE BOLETA*/
DELIMITER $$
CREATE PROCEDURE SP_REGISTRAR_DETALLE_BOLETA
(
NBOL	CHAR(8),
CODPRO	CHAR(5),
CANTI		INT,
IMPOR		DECIMAL(8,2)
)
BEGIN
INSERT INTO DETALLE_BOLETA VALUES(NBOL,CODPRO,CANTI,IMPOR);
END;